// alert("Working");
let likeCount=0;
function like(){
    likeCount++;
    document.querySelector(".likecount").innerHTML=likeCount
}
document.querySelector(".flag1").addEventListener("click",language1);
document.querySelector(".flag2").addEventListener("click",language2);
document.querySelector(".flag3").addEventListener("click",language3);
document.querySelector(".flag4").addEventListener("click",language4);
document.querySelector(".flag5").addEventListener("click",language5);



function language1(){
    document.querySelector("h1.title1").innerHTML="Qual è la mia estetica?";
    document.querySelector("p.content1").innerHTML="Qual è la mia estetica? Rispondi ora e il nostro cercatore estetico ti dirà se sei glam, spettrale, spigoloso o naturale. Trova la tua estetica e il tuo io più vero quando rispondi all'importante domanda: qual è la mia estetica?"
    document.querySelector(".btn1").innerHTML="INIZIO";
    document.querySelector("h3.title2").innerHTML="Come trovare la tua estetica"
    document.querySelector("h3.title3").innerHTML="Trova la mia estetica"
    document.querySelector("h3.title4").innerHTML="Divertente ricerca estetica"
    document.querySelector("h3.title5").innerHTML="Qual è l'estetica della mia migliore amica?"
    document.querySelector("p.content2").innerHTML="Dicci cosa ne pensi veramente del glitter e troveremo la tua estetica. Alcune domande sui tuoi amici e sul tuo stile sono tutto ciò che serve per capire dove si inserisce il tuo look e che tipo di atmosfera porti alla festa."
    document.querySelector("p.content3").innerHTML="Che estetica sono? L'unico modo per scoprirlo è rispondere onestamente. Segui il tuo intuito e prenditi il ​​tuo tempo per rispondere a tutte le domande di questo quiz online. Più sarai onesto, più fedele sarà per te questo test estetico."
    document.querySelector("p.content4").innerHTML="Il nostro quiz estetico non è supportato da ricerche scientifiche, ma apprendere i risultati può influenzare il tuo senso dello stile. Sia che tu stia cercando un nuovo look o che desideri perfezionare la tua estetica attuale."
    document.querySelector("p.content5").innerHTML="Se i tuoi amici si chiedono quale sia il loro senso dello stile, condividi ora il nostro quiz What's My Aesthetic per scoprire che tipo di vibrazioni emanano. Riceverai anche un grafico a torta che mostra come ti confronti con l'estetica di altri quiz di Quizony."
    document.getElementById("id1").innerHTML="Qual è la mia estetica?"
    document.getElementById("id2").innerHTML="Ti sei mai chiesto, qual è la mia estetica? Sei ancora un po' confuso su dove ti collochi nei tanti tipi di estetica?<br><br>Il tuo stile è più naturale o preferisci un gusto personale che sia glamour, spigoloso o maschiaccio?<br><br>Man mano che cresciamo e maturiamo, definire la tua estetica è una delle cose sviluppate lungo il percorso. La tua sensibilità nel limitare la tua estetica è ai massimi livelli di sempre?<br><br> Allora non hai tempo da perdere.Determinare dove ti adatti tra la pletora di tipi di estetica non dovrebbe causare stress o frustrazione.<br><br>Elimina il dolore, l'incertezza e la sensibilità che derivano dal non sentirti come se sapessi chi sei o dove ti trovi facendo questo divertente e facile quiz sull'estetica in questo momento.<br><br>Per favore rispondi velocemente a tutte le domande senza cercare di ragionare troppo. La tua prima reazione è spesso la tua migliore risposta ed è così che possiamo darti le risposte più accurate su dove ti adatti ai tipi di etichette estetiche possibili.<br><br>Le domande includeranno il tuo gusto, stile e personalità per aiutarti a scoprire dove appartieni. Sii onesto e scegli la risposta più vicina a chi sei per rispondere alla domanda, qual è la mia estetica? Riporta la tua fiducia al punto in cui dovrebbe iniziare proprio ora!"
    document.querySelector(".btn2").innerHTML="Inizia il quiz";
}
function language2(){
    document.querySelector("h1.title1").innerHTML="Quelle est mon esthétique ?";
    document.querySelector("p.content1").innerHTML="Quelle est mon esthétique ? Répondez maintenant et notre chercheur d'esthétique vous dira si vous êtes glam, effrayant, nerveux ou au naturel. Trouvez votre esthétique et votre vrai moi lorsque vous répondez à la question importante de - quelle est mon esthétique ?"
    document.querySelector(".btn1").innerHTML="DEMERRAR";
    document.querySelector("h3.title2").innerHTML="Comment trouver votre esthétique"
    document.querySelector("h3.title3").innerHTML="Recherche esthétique amusante"
    document.querySelector("h3.title4").innerHTML="Trouver mon esthétique"
    document.querySelector("h3.title5").innerHTML="Quelle est l'esthétique de ma meilleure amie ?"
    document.querySelector("p.content2").innerHTML="Dites-nous ce que vous pensez vraiment des paillettes et nous trouverons votre esthétique. Quelques questions sur vos amis et votre style suffisent pour déterminer où votre look s'intègre et quel genre d'ambiance vous apportez à la fête."
    document.querySelector("p.content3").innerHTML="Notre quiz esthétique n'est pas soutenu par des recherches scientifiques, mais l'apprentissage de vos résultats peut influencer votre sens du style. Que vous recherchiez un nouveau look ou que vous souhaitiez perfectionner votre esthétique actuelle."
    document.querySelector("p.content4").innerHTML="Quelle esthétique suis-je ? La seule façon de le savoir est de répondre honnêtement. Suivez votre intuition et prenez votre temps pour répondre à toutes les questions de ce quiz en ligne. Plus vous êtes honnête, plus ce test esthétique vous sera fidèle."
    document.querySelector("p.content5").innerHTML="Si vos amis s'interrogent sur leur propre sens du style, partagez dès maintenant notre quiz sur l'esthétique pour découvrir le type d'ambiance qu'ils dégagent. Vous obtiendrez également un diagramme circulaire montrant comment vous vous comparez à l'esthétique des autres quiz Quizony"
    document.getElementById("id1").innerHTML="Quelle est mon esthétique ?"
    document.getElementById("id2").innerHTML="Vous êtes-vous déjà demandé quelle est mon esthétique ? Êtes-vous encore un peu confus quant à votre place dans les nombreux types d'esthétique?<br><br>Votre style est-il plus naturel ou préférez-vous un goût personnel glamour, audacieux ou garçon manqué ?<br><br>Au fur et à mesure que nous grandissons et mûrissons, la définition de votre esthétique est l'une des choses développées en cours de route. Votre sensibilité à la limitation de votre esthétique est-elle à l'un des plus hauts niveaux de tous les temps ? Ensuite, vous n'avez pas de temps à perdre.<br><br>Déterminer où vous vous situez parmi la pléthore de types d'esthétique ne devrait pas vous faire ressentir du stress ou de la frustration.<br><br>Éliminez la douleur, l'incertitude et la sensibilité qui accompagnent le fait de ne pas avoir l'impression de savoir qui vous êtes ou où vous vous situez en répondant dès maintenant à ce quiz amusant et facile sur l'esthétique.<br><br>Veuillez répondre rapidement à toutes les questions sans essayer de trop raisonner. Votre première réaction est souvent votre meilleure réponse, et c'est ainsi que nous pouvons vous donner les réponses les plus précises sur l'endroit où vous vous situez dans les types d'étiquettes esthétiques possibles.<br><br>Les questions comprendront vos goûts, votre style et votre personnalité pour vous aider à découvrir où vous appartenez. Soyez honnête et choisissez la réponse la plus proche de qui vous êtes pour répondre à la question, quelle est mon esthétique ? Reprenez confiance en vous là où elle est censée commencer dès maintenant !"
    document.querySelector(".btn2").innerHTML="Commencer le  quiz";
}
function language3(){
    document.querySelector("h1.title1").innerHTML="Was ist meine Ästhetik?";
    document.querySelector("p.content1").innerHTML="Was ist meine Ästhetik? Antworten Sie jetzt und unser ästhetischer Finder sagt Ihnen, ob Sie glamourös, gruselig, kantig oder natürlich sind. Finden Sie Ihre Ästhetik und Ihr wahres Selbst, wenn Sie die wichtige Frage beantworten: Was ist meine Ästhetik?"
    document.querySelector(".btn1").innerHTML="START";
    document.querySelector("h3.title2").innerHTML="So finden Sie Ihre Ästhetik"
    document.querySelector("h3.title3").innerHTML="Lustiger ästhetischer Finder"
    document.querySelector("h3.title4").innerHTML="Finde meine Ästhetik A"
    document.querySelector("h3.title5").innerHTML="Was ist die Ästhetik meiner BFF?"
    document.querySelector("p.content2").innerHTML="Unser ästhetisches Quiz basiert nicht auf wissenschaftlichen Untersuchungen, aber das Erlernen Ihrer Ergebnisse kann Ihr Stilgefühl beeinflussen. Egal, ob Sie auf der Suche nach einem neuen Look sind oder Ihre aktuelle Ästhetik perfektionieren möchten."
    document.querySelector("p.content3").innerHTML="Welche Ästhetik bin ich? Der einzige Weg, das herauszufinden, ist ehrlich zu antworten. Folge deiner Intuition und nimm dir Zeit, um jede Frage in diesem Online-Quiz zu beantworten. Je ehrlicher Sie sind, desto treuer wird Ihnen dieser ästhetische Test sein."
    document.querySelector("p.content4").innerHTML="Sagen Sie uns, was Sie wirklich von Glitzer halten und wir finden Ihre Ästhetik. Ein paar Fragen zu deinen Freunden und deinem Style genügen, um herauszufinden, wo dein Look reinpasst und welche Stimmung du mit auf die Party bringst."
    document.querySelector("p.content5").innerHTML="Wenn Ihre Freunde sich über ihren eigenen Stil wundern, teilen Sie jetzt unser Was ist meine Ästhetik-Quiz, um herauszufinden, welche Art von Vibes sie ausstrahlen. Sie erhalten auch ein Kreisdiagramm, das zeigt, wie Sie im Vergleich zur Ästhetik anderer Quizony-Quizzer abschneiden."
    document.getElementById("id1").innerHTML="Was ist meine Ästhetik?"
    document.getElementById("id2").innerHTML="Haben Sie sich jemals gefragt, was meine Ästhetik ist? Sind Sie immer noch ein wenig verwirrt, wo Sie in die vielen Arten von Ästhetik passen?<br><br>Ist Ihr Stil eher natürlich oder bevorzugen Sie einen persönlichen Geschmack, der glamourös, kantig oder burschikos ist?<br><br>Während wir wachsen und reifen, ist die Definition Ihrer Ästhetik eines der Dinge, die sich auf diesem Weg entwickelt haben. Ist Ihre Sensibilität für die Einschränkung Ihrer Ästhetik auf einem der höchsten Niveaus aller Zeiten? Dann haben Sie keine Zeit zu verlieren.<br><br>Die Bestimmung, wo Sie in der Fülle von Ästhetiken Platz finden, sollte Sie nicht unter Stress oder Frustration treiben.<br><br>Beseitigen Sie den Schmerz, die Unsicherheit und die Sensibilität, die mit dem Gefühl einhergehen, nicht zu wissen, wer Sie sind oder wo Sie hingehören, indem Sie jetzt dieses unterhaltsame und einfache Quiz über Ästhetik machen.<br><br>Bitte beantworten Sie alle Fragen schnell, ohne zu viel zu argumentieren. Ihre erste Reaktion ist oft die beste Antwort, und so können wir Ihnen die genauesten Antworten geben, wo Sie in die möglichen Arten von ästhetischen Etiketten passen.Bitte beantworten Sie alle Fragen schnell, ohne zu viel zu argumentieren. Ihre erste Reaktion ist oft die beste Antwort, und so können wir Ihnen die genauesten Antworten geben, wo Sie in die möglichen Arten von ästhetischen Etiketten passen.<br><br>Die Fragen umfassen Ihren Geschmack, Stil und Ihre Persönlichkeit, um Ihnen zu helfen, herauszufinden, wo Sie hingehören. Seien Sie ehrlich und wählen Sie die Antwort, die Ihrer Person am nächsten kommt, um die Frage zu beantworten: Was ist meine Ästhetik? Holen Sie sich Ihr Selbstvertrauen dorthin zurück, wo es jetzt beginnen soll!"
    document.querySelector(".btn2").innerHTML="Quiz starten";
}
function language4(){
    document.querySelector("h1.title1").innerHTML="¿Cuál es mi estética?";
    document.querySelector("p.content1").innerHTML="¿Cuál es mi estética? Responde ahora y nuestro buscador de estética te dirá si eres glamoroso, espeluznante, nervioso o natural. Encuentra tu estética y tu yo más auténtico cuando respondas a la importante pregunta de: ¿cuál es mi estética?"
    document.querySelector(".btn1").innerHTML="COMEINZO";
    document.querySelector("h3.title2").innerHTML="Cómo encontrar tu estética"
    document.querySelector("h3.title3").innerHTML="Buscador de estética divertida"
    document.querySelector("h3.title4").innerHTML="Encuentra mi estética"
    document.querySelector("h3.title5").innerHTML="¿Cuál es la estética de mi mejor amiga?"
    document.querySelector("p.content2").innerHTML="Cuéntanos cómo te sientes realmente con el brillo y encontraremos tu estética. Unas cuantas preguntas sobre tus amigos y tu estilo son todo lo que necesitas para saber dónde encaja tu estilo y qué tipo de ambiente aportas a la fiesta."
    document.querySelector("p.content3").innerHTML="Nuestro cuestionario de estética no está respaldado por investigaciones científicas, pero conocer sus resultados puede influir en su sentido del estilo. Ya sea que esté buscando un nuevo look o quiera perfeccionar su estética actual."
    document.querySelector("p.content4").innerHTML="¿Qué estética soy? La única forma de averiguarlo es responder con sinceridad. Siga su intuición y tómese su tiempo para responder todas las preguntas de este cuestionario en línea. Cuanto más honesto seas, más fiel te será esta prueba estética."
    document.querySelector("p.content5").innerHTML="Si tus amigos se preguntan sobre su propio sentido del estilo, comparte ahora nuestro cuestionario ¿Cuál es mi estética? También obtendrá un gráfico circular que muestra cómo se compara con la estética de otros cuestionarios de Quizony."
    document.getElementById("id1").innerHTML="¿Cuál es mi estética?"
    document.getElementById("id2").innerHTML="Haben Sie sich jemals gefragt, was meine Ästhetik ist? Sind Sie immer noch ein wenig verwirrt, wo Sie in die vielen Arten von Ästhetik passen?<br><br>Ist Ihr Stil eher natürlich oder bevorzugen Sie einen persönlichen Geschmack, der glamourös, kantig oder burschikos ist?<br><br>Während wir wachsen und reifen, ist die Definition Ihrer Ästhetik eines der Dinge, die sich auf diesem Weg entwickelt haben. Ist Ihre Sensibilität für die Einschränkung Ihrer Ästhetik auf einem der höchsten Niveaus aller Zeiten? Dann haben Sie keine Zeit zu verlieren.<br><br>Die Bestimmung, wo Sie in der Fülle von Ästhetiken Platz finden, sollte Sie nicht unter Stress oder Frustration treiben.<br><br>Beseitigen Sie den Schmerz, die Unsicherheit und die Sensibilität, die mit dem Gefühl einhergehen, nicht zu wissen, wer Sie sind oder wo Sie hingehören, indem Sie jetzt dieses unterhaltsame und einfache Quiz über Ästhetik machen.<br><br>Bitte beantworten Sie alle Fragen schnell, ohne zu viel zu argumentieren. Ihre erste Reaktion ist oft die beste Antwort, und so können wir Ihnen die genauesten Antworten geben, wo Sie in die möglichen Arten von ästhetischen Etiketten passen.Bitte beantworten Sie alle Fragen schnell, ohne zu viel zu argumentieren. Ihre erste Reaktion ist oft die beste Antwort, und so können wir Ihnen die genauesten Antworten geben, wo Sie in die möglichen Arten von ästhetischen Etiketten passen.<br><br>Die Fragen umfassen Ihren Geschmack, Stil und Ihre Persönlichkeit, um Ihnen zu helfen, herauszufinden, wo Sie hingehören. Seien Sie ehrlich und wählen Sie die Antwort, die Ihrer Person am nächsten kommt, um die Frage zu beantworten: Was ist meine Ästhetik? Holen Sie sich Ihr Selbstvertrauen dorthin zurück, wo es jetzt beginnen soll!"
    document.querySelector(".btn2").innerHTML="Inciar prueba";
}

function language5(){
    document.querySelector("h1.title1").innerHTML="Mikä on esteettinen?";
    document.querySelector("p.content1").innerHTML="Mikä on esteettinen? Vastaa nyt, ja esteettinen löytömme kertoo sinulle, oletko glam, aavemainen, ärtyisä vai au natural. Löydä esteettinen ja todellisin itsesi, kun vastaat tärkeään kysymykseen - mikä on esteettinen?"
    document.querySelector(".btn1").innerHTML="AlKAA";
    document.querySelector("h3.title2").innerHTML="Kuinka löytää esteettinen"
    document.querySelector("h3.title3").innerHTML="Hauska esteettinen etsin"
    document.querySelector("h3.title4").innerHTML="Löydä esteettinen"
    document.querySelector("h3.title5").innerHTML="Mikä on BFF: n estetiikka?"
    document.querySelector("p.content2").innerHTML="Kerro meille, miltä sinusta todella tuntuu kimalluksesta, niin löydämme esteettisyytesi. Muutama kysymys ystävistäsi ja tyylistäsi riittää selvittämään, mihin ulkoasusi sopii ja millaista tunnelmaa juhliin tuodaan."
    document.querySelector("p.content3").innerHTML="Esteettinen tietokilpailumme ei tue tieteellistä tutkimusta, mutta tulostesi oppiminen voi vaikuttaa tyyliin. Etsitpä sitten uutta ulkoasua tai haluat täydentää nykyistä esteettisyyttäsi."
    document.querySelector("p.content4").innerHTML="Mikä esteettinen olen? Ainoa tapa saada selville on vastata rehellisesti. Seuraa intuitiotasi ja vie aikaa vastata kaikkiin tämän online-tietokilpailun kysymyksiin. Mitä rehellisempi olet, sitä totta sinulle tämä esteettinen testi on."
    document.querySelector("p.content5").innerHTML="Jos ystäväsi ihmettelevät omaa tyyliään, jaa Mikä on minun esteettinen -kyselymme saadaksesi selville, millaista tunnelmaa he antavat. Saat myös ympyräkaavion, joka näyttää, miten verrataan muiden Quizony-quizzereiden esteettisyyteen."
    document.getElementById("id1").innerHTML="Mikä on esteettinen?"
    document.getElementById("id2").innerHTML="Haben Sie sich jemals gefragt, was meine Ästhetik ist? Sind Sie immer noch ein wenig verwirrt, wo Sie in die vielen Arten von Ästhetik passen?<br><br>Ist Ihr Stil eher natürlich oder bevorzugen Sie einen persönlichen Geschmack, der glamourös, kantig oder burschikos ist?<br><br>Während wir wachsen und reifen, ist die Definition Ihrer Ästhetik eines der Dinge, die sich auf diesem Weg entwickelt haben. Ist Ihre Sensibilität für die Einschränkung Ihrer Ästhetik auf einem der höchsten Niveaus aller Zeiten? Dann haben Sie keine Zeit zu verlieren.<br><br>Die Bestimmung, wo Sie in der Fülle von Ästhetiken Platz finden, sollte Sie nicht unter Stress oder Frustration treiben.<br><br>Beseitigen Sie den Schmerz, die Unsicherheit und die Sensibilität, die mit dem Gefühl einhergehen, nicht zu wissen, wer Sie sind oder wo Sie hingehören, indem Sie jetzt dieses unterhaltsame und einfache Quiz über Ästhetik machen.<br><br>Bitte beantworten Sie alle Fragen schnell, ohne zu viel zu argumentieren. Ihre erste Reaktion ist oft die beste Antwort, und so können wir Ihnen die genauesten Antworten geben, wo Sie in die möglichen Arten von ästhetischen Etiketten passen.Bitte beantworten Sie alle Fragen schnell, ohne zu viel zu argumentieren. Ihre erste Reaktion ist oft die beste Antwort, und so können wir Ihnen die genauesten Antworten geben, wo Sie in die möglichen Arten von ästhetischen Etiketten passen.<br><br>Die Fragen umfassen Ihren Geschmack, Stil und Ihre Persönlichkeit, um Ihnen zu helfen, herauszufinden, wo Sie hingehören. Seien Sie ehrlich und wählen Sie die Antwort, die Ihrer Person am nächsten kommt, um die Frage zu beantworten: Was ist meine Ästhetik? Holen Sie sich Ihr Selbstvertrauen dorthin zurück, wo es jetzt beginnen soll!"
    document.querySelector(".btn2").innerHTML="Aloita tietokilpailu";
}